version: '3.3'
services:
  nginx:
    build:
      context: .docker/
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    volumes:
      - ./app:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: .docker/
      dockerfile: ./php/Dockerfile
    networks:
      - backend
    volumes:
      - ./app/:/var/www/html/
      - ./logs/php/:/var/log/
    ports:
      - "9000:9000"
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
      - "3307:3307"
    volumes:
      - mariadb_data:/bitnami
    networks:
      - backend

  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - phpmyadmin_data:/bitnami
    networks:
      - backend

  maildev:
    image: maildev/maildev
    container_name: app_maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    restart: always
    networks:
      - backend
    ports:
      - "1080:80"
      - "1025:25"
#
#  adminer:
#    image: adminer
#    container_name: "${ADMINER_NAME}"
#    restart: always
#    ports:
#      - 8080:8080
#    networks:
#      - backend
#    env_file:
#      - ".env.local"
#
#
#  maildev:
#    image: maildev/maildev
#    container_name: app_maildev
#    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
#    restart: always
#    networks:
#      - backend
#    ports:
#      - 1080:80
#      - 1025:25
#    env_file:
#      - ".env.local"
#
networks:
  backend:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  phpmyadmin_data:
    driver: local